version: '3'
services:

    #Laravel App
    app:
        build:
            context: .
            dockerfile: php/Dockerfile
        image: hakase-labs/laravel
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./jobar:/var/www/html
            - ./php/env/.env:/var/www/html/.env
        networks:
            - jobar_net

    #Nginx Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./jobar:/var/www/html
            - ./php/env/.env:/var/www/html/.env
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/ssl/:/etc/nginx/ssl/
        networks:
            - jobar_net

    #MySQL Service
    db:
        build:
            context: ./
            dockerfile: mysql/Dockerfile
        image: jobar_mysql:1.0
        container_name: jobar_mysql

        ports: 
            - "3306:3306"
        command:
            --explicit_defaults_for_timestamp=true

        environment:
            MYSQL_DATABASE: jobar
            MYSQL_USER: jobar
            MYSQL_PASSWORD: jobar123
            MYSQL_ROOT_PASSWORD: jobar123 
            TZ : Asia/Taipei
        volumes:
            - ./mysql/mysql_data:/var/lib/mysql

        networks:
            - jobar_net
        restart: always

#Docker Networks
networks:
    jobar_net:
        driver: bridge

#Volumes
volumes:
    mysqldata:
        driver: local